import {StyledWrapper} from './styled';
import { Card, Row, Col } from 'antd';
import { Upload, message } from 'antd';
import { InboxOutlined } from '@ant-design/icons';

const { Dragger } = Upload;
const props = {
    name: 'file',
    multiple: true,
    action: 'https://www.mocky.io/v2/5cc8019d300000980a055e76',
    onChange(info) {
      const { status } = info.file;
      if (status !== 'uploading') {
      }
      if (status === 'done') {
        message.success(`${info.file.name} file uploaded successfully.`);
      } else if (status === 'error') {
        message.error(`${info.file.name} file upload failed.`);
      }
    },
    onDrop(e) {
    },
  };

export default function Contract(){
    return (
        <StyledWrapper>
            <div className='contract-container'>
                <Row id='contract-window' gutter={16}>
                    <Col span={14}>
                        <Card title="Your contract:" bordered={false}>
                        <Dragger {...props}>
                            <p className="ant-upload-drag-icon">
                            <InboxOutlined />
                            </p>
                            <p className="ant-upload-text">Click or drag file to this area to upload</p>
                            <p className="ant-upload-hint">
                            Supports JSON Contract data generated by Truffle and HardHat. JSON File should contain ABI, address and contract name
                            </p>
                        </Dragger>
                        </Card>
                    </Col>
                    <Col span={10}>
                        <Card className='contract-events' title="Contract Events">
                            content !!!
                        </Card>
                    </Col>
                </Row>
            </div>
        </StyledWrapper>
    )
}